<div class="container-fluid">
    <!-- Breadcrumb -->
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="index/index">Home</a></li>
        <li class="breadcrumb-item"><a href="investmentSubgroup/index">Sub-grupos de investimentos</a></li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Sub-grupos de investimentos</strong>
                    <div class="card-actions">
                        <a onclick="location='investmentSubgroup/edit'"><i class="icon-plus"></i></a>
                    </div>           
                </div>
                <div  class="card-block">
                    <table class="table table-responsive table-hover table-outline mb-0">
                        <thead class="thead-default">
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>  
                                <th></th>  
                            </tr>
                        </thead>
                        <?php foreach ($investmentsubgroups as $investmentsubgroup): ?> 
                            <tr>
                                <td><?php echo $investmentsubgroup['id'] ?></td>
                                <td><?php echo $investmentsubgroup['name'] ?></td>            
                                <td>
                                    <a class="btn btn-link" href="investmentSubgroup/edit/id/<?php echo $investmentsubgroup['id'] ?>"
                                       >Editar</a>
                                </td>            
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
