<div class="container-fluid">
    <!-- Breadcrumb -->
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="index/index">Home</a></li>
        <li class="breadcrumb-item"><a href="user/index">Usuários</a></li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Usuários</strong>
                    <div class="card-actions">
                        <a onclick="location='user/edit'"><i class="icon-plus"></i></a>
                    </div>           
                </div>
                <div  class="card-block">
                    <table class="table table-responsive table-hover table-outline mb-0">
                        <thead class="thead-default">
                            <tr>
                                <th>ID</th>
                                <th>Usuário</th>  
                                <th>Tipo</th>  
                                <th></th>  
                            </tr>
                        </thead>
                        <?php foreach ($users as $user): ?> 
                            <tr>
                                <td><?php echo $user['id'] ?></td>
                                <td><?php echo $user['name'] ?></td>            
                                <td><?php echo $user['type'] ?></td>            
                                <td>
                                    <a class="btn btn-link" href="user/edit/id/<?php echo $user['id'] ?>"
                                       >Editar</a>

                                    <a class="btn btn-link" href="userChangeType/typeSet/id/<?php echo $user['id'] ?>"
                                       >Alterar tipo</a>
                                </td>            
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
