<div class="container-fluid m-3">
    <div class="row">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">
                    <h5>Redefinir senha</h5>
                </div>
                <div  class="card-body">
                    <form action="<?php echo BASE_URL ?>userResetPassword/request" method="post">
                        <input type="hidden" name="id" value="<?php echo isset($user['id']) ? $user['id'] : 0 ?>"/>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="email">Digite seu e-mail de cadastro</label>
                                    <input type="text" class="form-control" name="email" placeholder="E-mail de cadastro"  required=""/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <input class="btn btn-primary" type="submit" value="Recuperar"/>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Erros Modal-->
<?php require_once '../app/view/layout/main-alert.php' ?>