<div class="container-fluid">
    <!-- Breadcrumb -->
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="index/index">Home</a></li>
        <li class="breadcrumb-item"><a href="userResetPassword/form">Redefinir senha</a></li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Redefinir senha</strong>
                    <div class="card-actions">
                        <a onclick="location='user/edit'"><i class="icon-plus"></i></a>
                    </div>           
                </div>
                <div  class="card-block">
                    <p>Foi enviado uma mensagem para o e-mail indicado, nela haverá um link, ao acessá-lo o processo prosseguirá.</p>
                </div>
            </div>
        </div>
    </div>
</div>