<div class="container-fluid">
    <!-- Breadcrumb -->
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="index/index">Home</a></li>
        <li class="breadcrumb-item"><a href="userChangePassword/passwordSet">Trocar senha</a></li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Usuários</strong>
<!--                    <div class="card-actions">
                        <a onclick="location='user/edit'"><i class="icon-plus"></i></a>
                    </div>           -->
                </div>
                <div  class="card-block">
                    <p class="alert alert-success">Sua senha foi definida com sucesso!</p>
                </div>
            </div>
        </div>
    </div>
</div>