<div class="container-fluid">
    <!-- Breadcrumb -->
    <br>
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="index/index">Home</a></li>
        <li class="breadcrumb-item"><a href="userChangePassword/passwordSet">Definição de Senha</a></li>
    </ol>
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Insira uma senha</strong>
                </div>
                <div  class="card-body">
                    <form action="<?php echo BASE_URL ?>userChangePassword/write" method="post">
                        <input type="hidden" name="token" value="<?php echo $token ?>"/>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label for="password">Senha</label>
                                    <input type="password" class="form-control" name="password" placeholder="Digite uma senha"  required=""/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label for="password2">Repita a senha</label>
                                    <input type="password" class="form-control" name="password2" placeholder="Repita a senha"  required=""/>
                                </div>
                            </div>
                        </div>
                        <div>
                            <input class="btn btn-primary" type="submit" value="Gravar"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>